### ISSUE TITLE
Hardcoded text

### ISSUE THREAD

**Issue by tisba73** [JoomShaper/SP-Easy-Image-Gallery#12]
In [modules/mod_speasyimagegallery/tmpl/albums.php](https://github.com/JoomShaper/SP-Easy-Image-Gallery/blob/master/modules/mod_speasyimagegallery/tmpl/albums.php) at line 75, the texts "Photos" and "Photo" are hardcoded instead of being retrieved from text file... It should be something like:
```php
Text::_('MOD_SPEASYIMAGEGALLERY_PHOTOS')
```
and 
```php
Text::_('MOD_SPEASYIMAGEGALLERY_PHOTO')
```
where both "MOD_SPEASYIMAGEGALLERY_PHOTOS" and "MOD_SPEASYIMAGEGALLERY_PHOTO" should be added to the text file

**Comment by siddik-web** [comment]
Thanks, we add this
